### ISSUE TITLE
Fuzzy matches return glitched results.

### ISSUE THREAD

**Issue by Houshalter** [sdailey/kiwi#2]
On [this link](https://topherhallquist.wordpress.com/2015/07/30/lesswrong-against-scientific-rationality/), I open up kiwi and it has the following:

![image](https://i.imgur.com/tCwjFQq.png?1)

These both link to the following nonsense url: https://www.reddit.comundefined/. This appears to be reproducible by refreshing the page.

**Comment by sdailey** [comment]
Wow I'm a horrible open sourcer - very sorry this went unnoticed.

Looks like this commit https://github.com/sdailey/kiwi/commit/3f9d2d6df3f3137e7f85411b1fbbeb4e76f2a9ec fixed the issue. I appreciate your feedback and let me know if the error can still be reproduced on your end :)
